cozy/cozy-notes

src/locales/fr.json
See https://github.com/cozy/cozy-notes/pull/7#pullrequestreview-333368691
=> fix: French translation

manifest.webapp
Adds french and english description for the app.
=> chore: Add app descriptions

manifest.webapp
We need settings perm to have a full featured cozy-bar
=> feat: Add permissions for cozybar

src/locales/en.json, src/locales/fr.json
Since https://github.com/cozy/cozy-notes/pull/33/files we don't need those strings anymore
=> refactor: Rm unused string

jest.config.js, package.json, test/jestLib/babel-transformer.js, test/jestLib/json-transformer.js, test/jestLib/setup.js
Now we have everything we need to create tests for this app...
=> tests: Configure jest to handle files

src/components/app.jsx
=> refactor: Remove not used classname

package.json, yarn.lock
ATM we have an issue with the CSS of cozy-sharing. Latest version fix it (since it brings the side effect)
=> fix: Upgrade sharing to fix css issue

src/lib/collab/stack-client.js, src/lib/collab/stack-client.spec.js
=> fix: Catchup didn't normalize the server data

src/hooks/useTitleChanges.js
If we have small tabs it's easier to have access to the note title first ;)
=> feat: Title first title and then app name

package.json, src/components/notes/editor.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
* Change button labels
* Uses the last version from cozy ui (with a "danger" button)
=> feat: Uses the updated exit confirmation modal

package.json, yarn.lock
=> fix: Unbreaks cozy-ui by  using 30.4.1

src/components/notes/List/NoteRow.jsx
The `onClick` was attached to the wrong component, `Icon` is too small.
=> fix: Make "…" click area bigger

src/components/app.jsx, src/components/notes/List/NoteRow.jsx, src/components/notes/add.jsx, src/components/notes/sharing.jsx, src/hooks/useFileWithPath.js, src/hooks/useForceSync.js, src/hooks/useNote.js, src/hooks/useReferencedFolderForNote.jsx, src/hooks/useReturnUrl.js, src/hooks/useServiceClient.js, src/hooks/useTitleChanges.js, src/hooks/useUser.js, src/lib/utils.js, src/lib/utils.spec.js
Set the editor as read-only for a share where we don't have write permissions
=> Set the editor as read-only for a share where we don't have write permissions

.travis.yml, src/components/notes/__snapshots__/saving-indicator.spec.js.snap, src/components/notes/saving-indicator.spec.js
I  don't know how the tests were not failing in #93 but here is the fix
=> fix: Translations for saving indicator

src/lib/debug.jsx
I try to gather debug data when someone has an error. Recent explorations lead me to Realtime and token errors. This PR does add some debug data to look into the next time
=> feat: Adds realtime and cozy-client to debug

manifest.webapp, package.json
=> feat: Bump to 1.8.0

src/components/notes/__snapshots__/back_from_editing.spec.jsx.snap, src/components/notes/back_from_editing.jsx, src/components/notes/back_from_editing.spec.jsx
We moved a function to cozy-clients but I forgot to update a component using it
=> fix: Go back to previous folderId

src/lib/collab/provider.js, src/lib/collab/provider.spec.js
We were not using the correct date in the saving indicator. This change fixes this.
=> fix: Show the last save date

src/components/notes/__snapshots__/saving-indicator.spec.js.snap, src/components/notes/saving-indicator.jsx, src/lib/utils.js, src/lib/utils.spec.js, src/locales/en.json, src/locales/fr.json
These wordings are for the saving indicator in the bottom right in large views (not displayed yet in small views). Thenew wordings are the one requested by @joel-costa for a better UX
=> feat: Change saving indicator wordings

package.json, yarn.lock
Updates Realtime to earn onvisibilitychange and the latest fixes
=> feat: Updates realtime to 3.7

src/components/notes/List/list.styl
Requested by https://trello.com/c/oWB5BhxK
to have the same design as Drive
=> fix: List left margin at 32px

.travis.yml, package.json
ATM we have an issue when deploying with this new system. I don't know why yet. 
see https://travis-ci.com/cozy/cozy-notes/builds/151705796#L726
=> Revert "chore: Publish on download and post on mattermost"

src/components/notes/List/NoteRow.jsx, src/components/notes/sharing.jsx, src/targets/browser/index.jsx
This PR adds sharing indications in the notes list.
=> feat: Show shared notes on list

src/components/notes/List/AppTitle.jsx, src/locales/en.json, src/locales/fr.json
Requested by PO since the list now includes notes shared by other peoples.
=> feat: Change list title for "Latest Notes"

src/components/notes/List/List.jsx, src/components/notes/List/NoteRow.jsx, src/components/notes/List/list.styl, src/components/notes/editor-loading.jsx
The UI of notes on mobile is close to broken, this PR gets things to an acceptable level 😅
Before:
After:
=> Mobile UI enhancements

src/components/notes/add.jsx
Last fix broke the creation of a note. I missed some
uses of the modified function. This changes fixes the problem
=> fix: Allows to create a note

package.json, yarn.lock
Forgot to do it before merging #145…
=> fix: Upgrade cozy-sharing

CODEOWNERS
This way we have automatic reviewers assigned to PRs.
=> feat: Add a CODEOWNERS file

manifest.webapp, package.json
=> chore: Upgrade app's version

package.json, yarn.lock
Upgrade Cozy-sharing to get this fix https://github.com/cozy/cozy-libs/commit/f1ebea9
=> fix: Upgrade sharing to fix issue with ReadOnly

manifest.webapp, package.json
=> chore: Upgrade version

manifest.webapp, package.json
=> Bump 1.17.0

src/components/app.jsx, src/lib/initFromDom.js, src/lib/utils.js, src/targets/browser/index.ejs, src/targets/browser/index.jsx, src/targets/browser/index.spec.jsx
Use the new cozy-client api to handle meta attributes
https://trello.com/c/AWo7cMDa/245-utilisation-de-data-cozy-%C3%A0-la-place-de-data-cozy
https://trello.com/c/OussPGRv/38-utilisation-de-data-cozy-%C3%A0-la-place-de-data-cozy
=> feat: upgrade cozy metadata management

src/locales/fr.json
*Please explain what this PR does here.*
Before merging this PR, the following things must have been done:
If this PR relies on changes in one of our internal libraries (cozy-client-js or cozy-ui, for example), please also do the following things:
*(If not, please remove this last section.)*
=> Fix wording

package.json, src/components/notes/List/EmptyComponent.jsx, src/components/notes/List/List.jsx, src/components/notes/List/NoteRow.jsx, src/components/notes/back_from_editing.jsx, src/constants/strings.ts, src/lib/helpers.ts, src/lib/image-upload-provider.ts, yarn.lock
Related to: https://trello.com/c/c2RsOcVv/63-%F0%9F%93%9D-notes-afficher-le-chemin-des-notes-dans-la-liste-j
Feature: adding link to note directory in drive app
Implementation: using existing components from cozy-ui and cozy-notes
=> feat: Add note url

package.json, src/components/notes/List/List.jsx, src/components/notes/List/NotePath.tsx, src/components/notes/List/NoteRow.jsx, src/components/notes/List/WithBreakpoints.tsx, src/components/notes/List/index.jsx, src/components/notes/List/list.styl, src/types/declarations.d.ts, src/types/enums.ts, yarn.lock
Related to: https://trello.com/c/bXVAxYj0/72-%F0%9F%93%9D-notes-mobile-afficher-le-chemin-des-notes-dans-la-liste-j https://trello.com/c/xTfcS4KC/73-lorsque-je-passe-sur-le-chemin-il-est-surlign%C3%A9-bleu-et-non-noir
Request: show note name in mobile
Implementation: create a WithBreakpoints component and improve responsive handling in List
=> feat: Improve list display in mobile view

src/components/notes/List/NoteRow.jsx, src/components/notes/sharing.jsx, src/locales/en.json, src/locales/fr.json
This adds sharing option in cozy list right menu.
=> feat: Add sharing button for each note in notes list

package.json, yarn.lock
This will fix a cache issue bug
=> feat: Bump `cozy-client` from `v23` to `v24`

src/components/notes/List/List.jsx, src/components/notes/List/index.jsx, src/components/notes/List/list.styl
https://trello.com/c/jceiFmJg/100-%F0%9F%93%9D-notes-ui-notes-recentes-nest-pas-au-m%C3%AAme-niveau-sil-ny-a-pas-de-notes
=> fix: Improve UI when no notes exist

src/styles/index.css
https://trello.com/c/GGMuFgYs/106-%F0%9F%93%9D-notes-bugs-barre-doutils-image
=> fix: Update floating toolbar zindex

src/components/header_menu.jsx, src/hooks/useFetchIcons.ts
Show static assets for unknown users
=> fix: display icons in public mode

src/hooks/useTitleChanges.js
=> fix: Allow tabbing out of the title

package.json, src/components/notes/List/NotePath.tsx, src/lib/helpers.ts, src/types/declarations.d.ts, yarn.lock
https://trello.com/c/Ntqibd4M/428-%F0%9F%90%9B-lapp-notes-mouvre-drive-dans-le-navigateur-plut%C3%B4t-que-lapp-amirale
=> fix: Stay in App Amirale when opening a Note

src/components/app.jsx
important: the styles won't be good, cozy-ui needs to be updated in another commit
=> fix: Display AppTitle on mobile

package.json, src/components/app.jsx, src/components/header_menu.jsx, src/components/notes/List/EmptyComponent.jsx, src/components/notes/List/NotePath.tsx, src/components/notes/List/NoteRow.jsx, src/components/notes/List/index.jsx, src/components/notes/List/list.styl, src/components/notes/back_from_editing.jsx, src/constants/routes.ts, src/constants/strings.ts, yarn.lock
This concerns only the sharing modal in the list component
=> feat: Handle sharing modal as route

src/components/app.jsx, src/components/notes/sharing.jsx, src/constants/routes.ts
This will allow to close or re-open the modal with browser navigation
=> feat: Make editor sharing modal a route

CHANGELOG.MD, src/components/notes/List/NotePath.tsx, src/components/notes/List/NoteRow.jsx, src/types/declarations.d.ts
=> feat: In note list, remove possibility to click on note path on mobile

CHANGELOG.MD, src/components/notes/back_from_editing.jsx, src/components/notes/editor.jsx
to sync the note with Cozy Drive
=> fix: Force sync when clicking on back button, in the note editor

src/components/header_menu.jsx
```
* Show back the sharing banner
```
=> fix(HeaderMenu): show back sharing banner

src/components/app.jsx, src/components/notes/new-route.jsx, src/constants/routes.ts, src/lib/utils.js
```
* add route to create a note
```
This addition is linked to the addition of a FAB button on cozy-home (cc: https://github.com/cozy/cozy-home/pull/1860).
=> feat: add route to create a note

package.json
```
* Bump version from 1.24.0 to 1.25.0
```
=> feat: bump version from 1.24.0 to 1.25.0

src/components/notes/List/NoteRow.jsx
```
* Open Share modal on recipient click
```
=> feat: Open Share modal on recipient click

src/components/notes/editor.jsx, src/components/notes/new-route.jsx
```
* Two notes were opened on FAB button click on AA
```
=> fix: Two notes opened on AA

package.json, yarn.lock
```
* Update cozy-scripts from 7.0.1 to 7.0.2
```
=> feat: Update cozy-scripts from 7.0.1 to 7.0.2

.bundlemonrc, .travis.yml, package.json, yarn.lock
=> chore: Add bundlemon

src/components/app.jsx, src/components/notes/back_from_editing.jsx, src/hooks/useReturnUrl.js
```
* Hide back button in public view
```
=> fix: Hide back button in public view

.tx/config, CONTRIBUTING.md, README.md
```
* Add the project on transifex with the API v3 configuration
```
=> chore: Add the project on transifex with the API v3 configuration

package.json, yarn.lock
```
* Update cozy-sharing to obtain the new design of the sharing modal
```
=> feat: Update cozy-sharing from 5.0.1 to 6.0.4

package.json, yarn.lock
This update fix the display of the owner on sharing modal
```
*  Update cozy-sharing from 6.0.4 to 6.0.5
```
=> feat: Update cozy-sharing from 6.0.4 to 6.0.5

package.json
```
* Publish to mattermost
```
=> chore: Send message to mattermost after publication

src/components/intents/SaveButton.jsx, src/components/notes/editor-view.styl, src/lib/collab/content.js, src/lib/collab/stack-client.js
Il n'y a pas de changelog car ce ne sont pas des correctifs par rapport à la précédente version de prod
=> Some fixes after testing the intent integration

src/targets/intents/index.jsx
pas de changelog ici, c'était un oubli
=> Add some provider for the intent view

src/locales/en.json, src/locales/fr.json
```
* Change title placeholder wording
```
=> feat: Change title placeholder wording

src/components/notes/editor_config.ts, src/lib/collab/schema.js, src/locales/atlassian_missing_french.json
```
* Add TaskList plugins
```
Need: https://github.com/cozy/editor-core/pull/3 
Also I need to check if I have to do something on the stack side.
=> feat: Add taskList item

package.json, src/components/app.jsx, src/components/header_menu.jsx, src/components/notes/List/NoteRow.jsx, src/components/notes/TrashedBanner.jsx, src/components/notes/editor.jsx, src/hooks/useNote.js, src/locales/en.json, src/locales/fr.json, yarn.lock
```
* Add trashed banner
```
**Related PRs:**
- https://github.com/cozy/cozy-ui/pull/2529
=> feat: Add trashed banner

src/constants/strings.ts, src/plugins/media/commands/helpers.ts, src/plugins/media/nodeviews/mediaNodeView/media.tsx
* It will now be possible to copy an image from an note to another one provided it is the same cozy instance owning both notes
=> fix: Allow copy pasting images from note to note (VO-125)

package.json, src/components/app.jsx, src/targets/browser/index.jsx, yarn.lock
```
* Add sentry to monitor crash event
```
=> feat: add Sentry (VO-334)

.bundlemonrc, src/components/notes/editor.jsx, src/hooks/useFixedToBottomOnIos.ts, src/lib/patches/fixedToBottomIos.ts
* Fixed toolbar position on iOS devices
https://github.com/cozy/cozy-notes/assets/12577784/17af8cf2-a9d2-4a28-b98f-c26d426cdc33
=> fix: make toolbar stuck to bottom with ios (VO-704)

src/targets/browser/index.jsx, src/targets/intents/index.jsx
```
* Add cozy-sharing css
```
=> feat: Add cozy-sharing css

package.json, src/components/app.jsx, src/styles/index.css, yarn.lock
```
* Add realtime on io.cozy.settings
* Adjust table and code block css to be more dark mode compliant
* Upgrade cozy-ui 109.1.1 to 110.1.0
```
=> Adjust table and code block css to be more dark mode compliant

package.json, yarn.lock
cf https://github.com/cozy/cozy-libs/pull/2648
=> feat: Upgrade cozy-sharing to 16.14.0

package.json, src/components/app.jsx, src/components/notes/EditorCorner.jsx, yarn.lock
And add `syncToCozySharingLink` with `addToCozySharingLink`
=> feat: Upgrade cozy-sharing and apply BC

package.json, yarn.lock
This reverts commit 354c3323d23f61d386c819de07f1a830747892a9.
=> Revert "feat: Upgrade cozy-dataproxy-lib for more defensive Provider"
