cozy/cozy-notes

- manifest.webapp
We usually separate the `Cozy` from the name field to help formatting in the UI.
> fix: Split name and prefix

- src/lib/collab/stack-client.js
Default title was missing because of a missing return in the function definition.
> fix: Default title was not defined

- src/lib/collab/channel.js
- src/lib/collab/provider.js
- src/lib/collab/stack-client.js
Before this change, if the server does not accept our modifications, we try to send them in a loop, until success. We noticed that if the server had a bug, this would flood the stack with unstoppable requests.
With this change, we implement an exponential backoff. We wait 128ms after the first failure, then double this amount each time until we succeed (and go back to 0ms). There is a maximum waiting time of 5 minutes (whatever the failure is, we will retry every 5 minutes)
This change also implement a catchup. After 4 failures in a row in sending new data to the server, we try to manually fetch changes from the server. This may resolve some out of sync situations.
> feat: Adds an exponential backoff when failing

- src/styles/index.styl
The app name in the Cozy-bar was at 11px instead of 1rem. This is the default for a browser and should have been overrided by cozy-ui.
Cozy-ui main stylesheet was missing. Fixed
> fix: Correctly load cozy-ui

- .travis.yml
Travis only runs on master, but for releases we also want to run on tags.
> chore: Build on tags

- .travis.yml
We want to build tags even if they don't start with a `v`.
> chore: Build without "v" prefix on tags

- package.json
- src/components/notes/hooks/useReferencedFolderForNote.jsx
- src/components/notes/list.jsx
- src/components/notes/list.styl
- src/lib/utils.js
- src/locales/en.json
- src/locales/fr.json
- src/targets/browser/index.jsx
- yarn.lock
This PR adds a link to the `Notes` folder created by the stack. We use the `referenced_folder` to fetch the folder. 
If the folder is not found (ATM we have a bug in the stack https://github.com/cozy/cozy-stack/pull/2287) we fallback to the Drive URL. 
I used markdown to put the URL in the message. But it comes with a drawback: we can't style the link... WDYT?
> feat: Add link to the Notes folder on Cozy Drive

- manifest.webapp
- src/locales/en.json
- src/locales/fr.json
cozy-scripts wants the manifest locales in the translation files, it strips the existing `locales` field from the manifest.
> fix: Move descriptions to locales

- src/components/notes/List/List.jsx
- src/components/notes/List/list.styl
Safari has an old bug with flex:1. We need 100% height
> fix: Safari height issue

- src/components/notes/editor.jsx
- src/lib/utils.js
The browser tab is now named with the title of the document. This will help the awesome bar of Firefox and Chrome, and will allow user to put the page in their favorites
> feat: Have the title on the tab bar of the browser

- src/components/notes/editor-loading.jsx
The loading screen for the editor did have a weird UI with a non-styled link back to the home page and an incomplete header bar.
It's now with a simple cozy-bar and a spinner in the content.
> feat: Don't show link to back when loading a note

- index.spec.jsx
- jest.config.js
We had an error when we tried to run an empty test. This error was the result of a not enough restrictive moduleNameMapper.
This is not the first time, we should pay attention to this.
> tests: Fix test command

- src/targets/browser/index.jsx
The sharing button was not going green when the note was shared. The "copy link" button didn't have the correct style.
During the last merge with master, we lost a few CSS. Here is the fix
> fix: Adds again the necessary stylesheets

- src/components/notes/editor-view.jsx
- src/components/notes/editor-view.styl
- src/styles/index.css
Since `Layout` adds a `before` with an height of 3rem (https://github.com/cozy/cozy-ui/blob/master/stylus/objects/layouts.styl#L105) on medium-screen to give to the bar the needed place and since we hide the cozy-bar, we had to remove this. I just used a -3rem marginTop
> fix: EditorBar issue on mobile

- src/components/notes/List/index.jsx
- src/components/notes/editor-view.styl
- src/styles/index.css
Avant, on cachait le ::before de cozy-ui pour lui mettre une hauteur de 0 principalement parce que nous cachons la cozy-bar sur l'`editeur-view`. Ça faisait sens quand on avait qu'une seule vue. Maintenant nous avons aussi le listing des notes, et cette vue doit hériter des styles traditionnels de UI à savoir ce fameux before de 3rem. 
Vu que l'editeur-view a un comportement particulier, je préfère lui appliquer le -3rem en margin que d'appliquer le comportement normal de UI sur les autres vues (donc j'ai retiré le mt-3 sur la liste qui n'a plus sens)
> fix: Remove the hide of o-layout-before. Change list's margin

- src/components/notes/editor-view.jsx
By reading the code, I don't think this `inherit` is mandatory. I can be wrong, and in that case having a comment to explain why this is needed could be very helpful
> refactor: No need of inherit

- manifest.webapp
- package.json
We just started the release process of the 1.4.0. Let's upgrade to 1.5.0
> chore: Bump version to 1.5.0

- package.json
- src/components/notes/editor.jsx
- src/lib/collab/channel.js
- src/lib/collab/channel.spec.js
- src/lib/collab/stack-client.js
- src/lib/collab/stack-client.spec.js
- src/lib/utils.js
- yarn.lock
With this change, we send a sync() request to the server
when leaving a note. This will allows the server to always
have files names and content up to date when we finish
to edit a note (instead of having to wait a few minutes).
Collateral: We now go back to the index with an anchor
and not by reloading the full page.
> feat: Sync on leaving a note

- src/hooks/useReferencedFolderForNote.jsx
Currently, we have a blank screen on mobile when we acceed the home page if we have no notes. 
This is because we start rendering an `<AppLinker>` (https://github.com/cozy/cozy-notes/blob/master/src/components/notes/List/EmptyComponent.jsx#L12) with an empty / undefined `href` resulting of on error since the AppLinker needs an url.
To fix this issue, we assign the default URL to the default hooks value
> fix: Set default value to Folderurl

- manifest.webapp
- package.json
1.5.0 was already deployed. Let's deploy 1.5.1 with a bugfix
> chore: Bump to 1.5.1

- package.json
- src/components/notes/editor-view.jsx
- src/components/notes/editor.jsx
- yarn.lock
Force a sync on the underlying io.cozy.file
when the user leave the title field.
This will force the io.cozy.file to update its
filename with the lastest title.
> feat: Force sync when leaving the title

- src/components/notes/editor-view.jsx
- src/components/notes/editor.jsx
- src/components/notes/sharing.jsx
- src/hooks/useCollabProvider.js
- src/hooks/useFetchNotesByIds.jsx
- src/hooks/useForceSync.js
- src/hooks/useNote.js
- src/hooks/useReturnUrl.js
- src/hooks/useServiceClient.js
- src/hooks/useTitleChanges.js
- src/hooks/useUser.js
- src/lib/collab/channel.js
- src/lib/collab/channel.spec.js
- src/lib/collab/provider.spec.js
- src/lib/collab/stack-client.js
- src/lib/collab/stack-client.spec.js
Tentative de refactorisation de &lt;Editor>
Objectif de limiter la complexité (je commençais à ne plus forcément voir toutes les interactions) et de permettre plus tard le test de la logique métier (qui me semblait plus que difficile à tester dans la forme monolithique)
> refactor: Simplify <Editor> with hooks

- package.json
- yarn.lock
Previously, saving requests were failing indefinitely when
the stack token had expired. An update of cozy-client
fixes that.
See https://github.com/cozy/cozy-client/pull/618
> fix: Refresh token

- package.json
- src/components/notes/back_from_editing.jsx
- src/components/notes/editor.jsx
- src/hooks/useCollaborationState.js
- src/locales/en.json
- src/locales/fr.json
- yarn.lock
Uses the last useConfirmationExit available in https://github.com/cozy/cozy-ui/pull/1366 to also warn about unsaved changes when the user clicks on the button to return to the list of notes.
> feat: Confirmation on exit when changing page

- src/components/notes/List/NoteRow.jsx
- src/locales/en.json
- src/locales/fr.json
ATM we only displayed the date of the last update. It can be useful to also have the time. 
This PR adds that. 
Just a WIP. Waiting to have the feedback from @joel-costa ;)
> feat: Display time for updated_at

- src/targets/browser/index.jsx
Without this, the bar would have its own version of React,
and then would break our hooks.
> fix: Force the bar to share our version of React

- src/locales/en.json
- src/locales/fr.json
Instead of implementing a full cancel system, we explain that the note is now in the trash (from which it can be restored, even though that is not explicit in the alert message).
> fix: Reword note delete message

- src/components/notes/editor-view.jsx
- src/components/notes/editor-view.spec.jsx
- src/components/notes/editor.jsx
- src/hooks/useCollabProvider.js
- src/lib/collab/provider.js
- src/lib/collab/provider.spec.js
<Editor> and <EditorView> now have a `readOnly` attributes. 
If readOnly: 
- The toolbar will not be greyed out
- The reader cannot type into the editor or into the title
- The reader will still see updates coming from the server
> feat: Allows to turn the editor read-only

- src/lib/utils.js
- src/lib/utils.spec.js
When the note is  present in the root dir, the link going back if invalid and send to an error page.
This change fixes that.
Note: I do not know nor understand why we were stripping "-"  in the folder ids. It's probably better to wait for @Crash-- approval before merging this PR
> fix: Goes back to root dir

- package.json
- src/components/app.jsx
- src/lib/utils.js
- src/lib/utils.spec.js
- yarn.lock
This changes add the ability to give an the file id as parameter
in the public route of a share. This is needed when the sharecode
is about multiple files or about a note.
This changes also take into account if the permission of the share code
states the share is read only or not.
> feat: Public route with share token for a parent folder

- src/hooks/useUser.js
- src/hooks/useUser.spec.js
- src/lib/collab/participant.js
- src/lib/utils.js
- src/lib/utils.spec.js
In collaboration mode, we show initials attached to each cursors. We also plan to display avatars in the future.
This PR allows a cozy to send the editor name when building a link, and have the correct name first letter.
It also remove old placeholder data (email and avatar) which are not displayed today but were throwing CSP errors in the console.
> feat: Allows a user provided username

- src/components/notes/editor.jsx
- src/hooks/useCollabProvider.js
- src/lib/collab/channel.js
- src/lib/collab/channel.spec.js
- src/lib/collab/provider.js
- src/lib/collab/provider.spec.js
- src/lib/collab/stack-client.js
Previously, the last saving date was initialized
with the time when the document was opened.
With this change, we reuse the updatedAt date
inside the document itself.
> feat: Shows date of previous doc update

- manifest.webapp
- package.json
We currently have a 1.10.0 in beta. Let's publish a 1.11.0-dev to check if the deployment works.
> chore: Bump vesion

- src/hooks/useUser.js
- src/hooks/useUser.spec.js
For a share by link, if the visitor does not provide an
explicit username, use '?' as initial for his cursors.
> feat: Initial of ? for unknown public user

- package.json
- src/components/notes/List/NoteRow.jsx
- src/lib/utils.js
- src/lib/utils.spec.js
- yarn.lock
Previously, clicking on a note in the index always redirect
to the editor's instance. This was creating duplicates and
conflicts when the note was created on another instance.
It now correctly redirects to the first author's instance.
> fix: Edit a note on the correct cozy instance

- src/components/notes/List/index.jsx
- src/components/notes/add.jsx
The update of cozy-client broke the "+" button on mobile.
The AddMobile component uses the withClient / useClient of the
new cozy-client, which relies on the new Context feature of React.
The bar only provides the old Context feature in its tree.
When the AddMobile is inserted into the bar, it cannot find the
cozyClient instance in the tree, and fails.
> fix: Notes creation on mobile

- src/components/notes/editor-view.jsx
- src/components/notes/editor.jsx
- src/hooks/useTitleChanges.js
- src/hooks/useTitleChanges.spec.js
Line feeds in title break both the title display in the note and the file name in couch.
> fix: Forbid carriage return and line feed in title

- src/targets/browser/index.jsx
We recently added the SharingProvider to get the sharing state. But we don't want to mount the SharingProvider if we're in a public context. Mounting it results by querying "shared-by-link" and other and throw errors.
> fix: Don't load SharingProvider if we're in a public context

- src/targets/browser/index.jsx
- src/targets/browser/index.spec.jsx
The Notes app was crashing when using a locale that wasn't supported (for example spanish). This PR makes the app default to a supported locale in that case.
> fix: Don't crash when the locale is not supported

- src/components/notes/List/NoteRow.jsx
II use the [vimium](https://addons.mozilla.org/fr/firefox/addon/vimium-ff/) browser
extension that allows me to highlight interactive elements when pressing the
`f` key. When I pressed this key while using cozy-notes, I couldn't reach the
notes list items.
I'm no a11y expert, but I found the reason was the following:
The whole row has an onClick handler that redirects to the note editor
when the user clicks the row. But since the rendered element is a div,
it was not properly seen as a button by the browser
Adding a button role and a tabIndex make it accessible. And to be complete, I
added a onKeyDown handler that redirects to the note when the user presses the
Enter key.
> feat(NoteRow): add button role

- src/components/notes/editor.jsx
- src/hooks/useNote.js
Previously, we tried to update the note's schema, even if the note was opened in read only. Since readOnly doesn't have the permission to update the schema an error was dispatched. 
So let's not update the schema if the note is opened in read only.
> fix: Don't update the schema if readOnly

- package.json
- src/components/app.jsx
- yarn.lock
Cozy-client v18 was bugged, the cozy-bar was crashed. 
Fix was released in v20 (https://github.com/cozy/cozy-client/pull/904#discussion_r595178498) . But hey let's update to the latest version. I've just fixed a BC.
> fix: Upgrade cozy-client

- package.json
- src/components/app.jsx
- src/lib/debug.jsx
- src/targets/browser/index.ejs
- yarn.lock
Post breaking changes from dependencies
Cozy-flags introduced breaking changes which were not detected earlier. This has been fixed in this mr. Also the dependency tree has been cleaned a bit.
All dependencies in the project are now up to date to their latest minor versions (except two).
No dependency has been updated to its next major version though as it seems risky to do everything at once.
> fix: update app init

- package.json
- yarn.lock
https://trello.com/c/HUipo7Qa/50-retour-4-regression-je-narrive-plus-%C3%A0-cr%C3%A9er-des-tableaux-dans-les-notes-erreur-en-console-uncaught-typeerror-e-is-undefined
editor-core as we use it (v134.0.1) will break with editor-tables > 1.1.3. It was necessary to update the resolution of this dependency. I don't think this is a long term solution, best would be to update editor-core itself but unsure at the moment what problems would it create with cozy-stack
> fix: force editor-tables resolution to editor-core

- src/components/notes/editor-view.jsx
- src/lib/image-upload-provider.ts
- src/locales/en.json
- src/locales/fr.json
- src/types/declarations.d.ts
- src/types/errors.ts
- src/types/guards.ts
Related to https://trello.com/c/y4QmVMRU/40-%F0%9F%93%9D-notes-affichage-derreur-si-upload-de-type-de-fichier-non-image
It is impossible to disallow the user to upload any kind of invalid file if he really wants to. The backend will error on such files. Thus, we will rely on it, there's no real gain to validate front-end side. That way we just wait to see if the upload failed with a 422, that will assure us the file is unprocessable. We just have to display an error alert for good UX as a way to handle this error.
> feat: handle invalid file uploads

- src/components/notes/editor-view.jsx
- src/constants/interface.ts
- src/lib/image-upload-provider.ts
- src/types/declarations.d.ts
This is a quick fix to improve loading states when uploading large images. It will block the page and show a 0.5 opacity black overlay with a spinner in its center. Main issue is for fast uploads, it will show up briefly. But for now it's better than having a page freely editable while we're actually waiting for an async op in a sync way to update the prosemirror tree.
> feat: Improve loading states

- package.json
- yarn.lock
It will allow cozy-notes to match cozy-libs' cozy-client version, which avoids bugs and duplicates.
> feat: Upgrade cozy-client version

- manifest.webapp
This is needed in order to implement cozy to cozy sharing.
It only allows GET requests.
> feat: Allow cozy-notes contacts access

- .gitignore
- CHANGELOG.MD
- manifest.webapp
- package.json
- src/components/app.jsx
- src/components/notes/editor-view.jsx
- src/components/notes/editor.jsx
- src/components/notes/sharing.jsx
- src/constants/strings.ts
- src/hooks/usePreview.ts
- src/styles/index.css
- yarn.lock
Related to: https://trello.com/c/AiQg5Cjr/16-%F0%9F%93%9D-notes-partage-cozy-%C3%A0-cozy-notes-4j
Features:
- Add a new route to allow users to preview a note from email sharing
- Allows `Notes` to interact with `Contacts` (necessary for sharing to work as intended)
- Render the new `SharingBannerPlugin` in `Editor`; which manages itself
- Update the sharing modal in order to allow a user to share a note by email
- Update editor CSS overrides in order to display the `SharingBannerPlugin` in a `cozy-drive` way
Caveats:
- There are some questions about the post-sharing view. Should it go to the shared note or (currently) the shared note folder?
- Some old code about link sharing might be outdated by now. Should we review it entirely or continue to let it manage link sharing?
> feat: Add cozy-to-cozy sharing

- src/styles/index.css
Related to https://trello.com/c/AiQg5Cjr/16-%F0%9F%93%9D-notes-partage-cozy-%C3%A0-cozy-notes-4j
This will fix unwanted UI behaviors. 
- Hide the avatar group banner
- Fix toolbar height
- Adapt cozy toolbar to that height
- Remove toolbars overlaps on small viewports
> fix: Improve css styles

- src/components/notes/List/NoteRow.jsx
- src/components/notes/List/list.styl
related to: https://trello.com/c/AiQg5Cjr/16-%F0%9F%93%9D-notes-partage-cozy-%C3%A0-cozy-notes-4j
We just use small CSS patches and change the size prop (value taken from Zeplin). Other solutions could be reworking the SharedRecipients component but at this point, I'm afraid of unintended side-effects in cozy-drive or elsewhere. Also, in terms of use, it makes sense that SharedRecipients does not necessarily know its border color in every scenario.
> fix: Update SharedRecipients styles to match drive

- src/components/notes/List/NotePath.tsx
- src/lib/helpers.spec.ts
- src/lib/helpers.ts
Related to: https://trello.com/c/wozfDjxO/75-%F0%9F%93%9D-notes-ne-pas-afficher-le-nom-dans-le-chemin-de-la-note-mais-que-son-chemin
Simply display the path of a note without `/{noteName}`  by using a small RegExp.exec() call
> feat: Remove filename

- src/components/notes/EditorCorner.jsx
- src/components/notes/editor.jsx
- src/components/notes/sharing.jsx
Use the updated title in real time in the sharing modal, not the title from the initial GET (which will never change until page refresh).
> feat: Use updated title in sharing modal

- src/components/notes/List/NoteRow.jsx
- src/components/notes/sharing.jsx
The application is broken without it (modal can't be closed etc). As it broke dev env a quick fix is required. A more thorough fix can be dealt with later
> fix: Rollback useCallback changes as it created a breaking bug

- app.config.js
- src/components/notes/editor-view.jsx
- src/constants/strings.ts
- src/lib/image-upload-provider.ts
- src/plugins/image-upload/event-handlers.ts
- src/plugins/image-upload/index.tsx
- src/plugins/image-upload/pm-plugins/actions.ts
- src/plugins/image-upload/pm-plugins/commands.ts
- src/plugins/image-upload/pm-plugins/input-rule.ts
- src/plugins/image-upload/pm-plugins/main.ts
- src/plugins/image-upload/pm-plugins/plugin-key.ts
- src/plugins/image-upload/types.ts
- src/plugins/image-upload/utils.ts
- src/plugins/media/README.md
- src/plugins/media/index.tsx
- src/plugins/media/nodeviews/mediaNodeView/index.tsx
- src/plugins/media/nodeviews/mediaSingle.tsx
- Atlaskit editor does not handle by default this feature
- It was impossible to activate it, nowhere in the codebase is it mentioned
- ProseMirror does have a plugin handling it, but Atlaskit does not use it
- Externalize `image-upload` plugin from Atlaskit to Cozy
- Add a function in that plugin that will set the editor selection to the drop location
- Improve image uploader to handle drop events
- Disallow the user to drop images outside ProseMirror with a global listener
> feat: Add drag and drop for images

- .eslintrc.json
- app.config.js
- src/components/app.jsx
- src/components/header_menu.jsx
- src/components/header_menu.styl
- src/components/notes/editor-view.jsx
- src/components/notes/editor.jsx
- src/constants/strings.ts
- src/locales/atlassian_missing_french.json
- src/styles/index.css
- src/ui/Dropdown/index.tsx
- src/ui/DropdownMenu/index.tsx
- src/ui/DropdownMenu/types.ts
- src/ui/with-outer-listeners.tsx
J'avais travaillé depuis le début en essayant de convertir la toolbar de drive en toolbar agnostique dans cozy-ui, malheureusement plus j'avançais plus j'avais l'impression de créer de la dette technique et de créer un composant très complexe avec beaucoup trop de props pour qu'il soit compatible à la fois avec drive et notes.
Etant insatisfait avec cela j'ai décidé d'annuler le travail qui était fait sur cozy-ui depuis la toolbar cozy-drive et j'ai recommencé from scratch sur cozy-notes, en utilisant cependant uniquement des composants déjà existants. Je n'ai malheureusement pas eu le temps de terminer cette approche en raison du switch trop tardif. Cela-dit, étant donné que les composants utilisés existent déjà, le MVP est fonctionnel.
En terme de reste à faire, il y a une anomalie sur …
> feat: Implement MVP header

- src/components/notes/List/NoteRow.jsx
https://trello.com/c/v8HGwuLB/93-%F0%9F%93%9D-notes-ui-mettre-un-message-derreur-quand-on-clique-sur-une-note-corrompue-exemple-404
> fix: Handle failure when opening a note

- src/components/HeaderNotePath.jsx
- src/components/header_menu.jsx
- src/components/notes/editor.jsx
- src/hooks/useFileWithPath.js
Related to https://trello.com/c/wpOZ52TO/95-%F0%9F%93%9D-notes-ne-pas-afficher-le-chemin-complet-dune-note-partag%C3%A9e
Using useFileWithPath() hook to get huiman readable filepath name
> fix: Properly display note path

- src/hooks/useTitleChanges.js
https://trello.com/c/cz5BooES/98-%F0%9F%93%9D-notes-pouvoir-sortir-du-titre-apr%C3%A8s-un-entr%C3%A9e
> fix: Allow tabbing out of the title

- package.json
- src/constants/strings.ts
- src/lib/utils.js
- src/lib/utils.spec.js
- src/targets/browser/index.jsx
- yarn.lock
When sharing cozy to cozy a note, we create a link to see
a preview.
Loading this preview from /preview?sharecode doesn't work
we need to load it from /preview/?sharecode.
> fix: Sharing cozy to cozy

- CHANGELOG.MD
- manifest.webapp
We forgot to upgrade the version in the manifest.webapp after releasing the 1.18.0. Upgrading packge.json is not enough, we have to upgrade both files.
> chore: Upgrade

- src/components/notes/sharing.jsx
If the user didn't write any title,
then the props.title is undefined
In that case, we fallback to the
file.attributes.names. It'll be something
like "New Note ...."
Cozy-Stack doesn't allow us to create
a sharing's rule with an empty string
as title.
> fix: Sharing note with empty title

- .travis.yml
xenial is still the default ubuntu version
on Travis, but do not have standart support
anymore.
So let's use the latest available LTS at this
time.
See https://wiki.ubuntu.com/Releases for
more informations about ubuntu support.
> chore: Upgrade ubuntu to focal

- src/components/notes/List/NoteRow.jsx
- src/components/notes/sharing.jsx
- src/constants/strings.ts
Somehow both sharing modals of cozy-notes ended with a "Files" docType,
which creates obviously many issues in terms of sharing privileges.
It is to be reviewed why these faulty changes were made in the first place.
To add to that, I don't think it is possible to test this to prevent future errors here. It's just direct props injection, so it's 100% declarative. A test would only be the implementation of what it is testing
> fix: Apply correct documentType on shareModals

- .eslintrc.json
- package.json
- src/components/app.jsx
- src/components/notes/List/NoteRow.jsx
- src/components/notes/List/index.jsx
- src/constants/routes.ts
- src/targets/browser/index.jsx
- yarn.lock
* Use <Route children> instead of <Route render> and/or <Route component> props
* Use our hooks API to access router state like the current location and params
* Replace all uses of withRouter with hooks
* Replace any <Route>s that are not inside a <Switch> with useRouteMatch, or wrap them in a <Switch>
> feat: Upgrade react-router-dom to v6.3.0

- package.json
- src/components/notes/List/AppTitle.jsx
- src/components/notes/__snapshots__/editor-view.spec.jsx.snap
- src/components/notes/__snapshots__/saving-indicator.spec.jsx.snap
- src/components/notes/back_from_editing.jsx
- src/components/notes/editor-view.jsx
- src/components/notes/saving-indicator.jsx
- yarn.lock
`BackFromEditing` button is responsible to redirect the app to the
`returnUrl` given in the URL's searchParams
In previous behaviour, in a Flagship mobile app, the resulting scenario
would be to call `openApp` with the given URL and the `drive` slug
However, the `drive` slug should not be forced. When the note is opened
from `cozy-notes` then the  `returnUrl` is the `cozy-notes` base url.
So instead we should guess the slug from the `returnUrl`
___
Related PR:
- https://github.com/cozy/cozy-client/pull/1217
- https://github.com/cozy/cozy-ui/pull/2206
___
TODO:
> fix: Do not force `drive` slug when clicking on `BackFromEditing` button

- CHANGELOG.MD
- src/components/HeaderNotePath.jsx
- src/hooks/useFileWithPath.js
- src/hooks/useFileWithPath.spec.js
https://trello.com/c/aGLLz7aD
Lors de la consultation d'une note, le lien vers son dossier dans le header n'était pas bon
> fix note folder path in HeaderNotePath

- src/components/notes/List/NoteRow.jsx
Note path was opened on another tab, while the note was opened on the current tab. The new behavior is to open the path on the current tab.
> fix: Open note path on the current tab

- src/constants/strings.ts
- src/targets/browser/index.jsx
```
*
* Correct preview path to show correct sharing banner for cozy to cozy sharing
*
```
My previous PR : https://github.com/cozy/cozy-notes/pull/344 only fix the problem to show the banner. Notes preview wasn't matching with cozy-sharing pathname so we show every time the public banner with this new fix we show also the name of the cozy owner.
> fix: preview path to match with cozy-sharing

- src/components/notes/List/NoteRow.jsx
red = before
blue = after
```
* Increase note row dots menu hit box on mobile
### Bugfix
* Fix text ellipsis on mobile note name
```
> feat: Increase note row dots menu hit box on mobile

- src/styles/index.css
We had misalignment between lines and lines number
because line-number-gutter doesn't have
the right padding-top.
Here we set it to 26px because:
- 12px (from .code-content padding top)
- + 14px (from pre margin top)
```
* Fix: Code line number alignment 
```
> fix: Alignment between code line and line number

- src/targets/browser/index.jsx
- src/targets/browser/index.spec.jsx
Shared note preview writable again because token from body had write access.
```
* Shared note previews are now writable if write access is granted.
```
> feat: Use token from body instead of sharecode in URL

- .bundlemonrc
This commit is preparation to track change of size after the split of vendors into two parts vendors and atlaskit : https://github.com/cozy/cozy-notes/pull/367
```
* Add groups on bundlemon
```
> chore: Add groups on bundlemon

- manifest.webapp
- package.json
```
* Bump version to 1.28.0
```
> chore: Bump version to 1.28.0

- package.json
- yarn.lock
This PR merge back fix from https://github.com/cozy/cozy-notes/tree/release/1.27.0
> feat: Update cozy-sharing from 6.0.4 to 6.0.5

- src/components/notes/editor-loading-error.jsx
- src/locales/en.json
- src/locales/fr.json
Quick fix 
```
* It was possible to inject style in this parameter. CSP was blocking javascript, so this was not too dangerous. 
```
We should rethink this returnURL parameter to see if it still needed or not and maybe check the domain. This param is used at least on Drive when creating a note, in order to go back to Drive when clicking on "Back" and not returning at the root of cozy-notes.
> fix: Escape returnURL parameter

- app.config.js
In commit 4b7c063097951f2158804f8160f11d7dd4547f4e, the '@atlaskit/calendar' module was removed from the webpack configuration. However, this module is still in use within the application in the DatePicker component of the Note editor.
This PR restores the reference to '@atlaskit/calendar' in the webpack config, fixing the issue introduced by the previous commit and ensuring the application functions as expected.
> Restore '@atlaskit/calendar' Module Reference

- .bundlemonrc
- config/webpack.bundle.default.js
- config/webpack.config.intents.js
- manifest.webapp
- package.json
- src/components/intents/IntentEditorView.jsx
- src/components/intents/IntentProvider.jsx
- src/components/intents/SaveButton.jsx
- src/components/notes/__snapshots__/editor-view.spec.jsx.snap
- src/components/notes/editor-view.jsx
- src/components/notes/editor-view.styl
- src/lib/collab/stack-client.js
- src/locales/en.json
- src/locales/fr.json
- src/targets/intents/index.ejs
- src/targets/intents/index.jsx
- yarn.lock
On ajoute la possibilité d'ouvrir l'éditeur de note via un intent. Depuis l'itent il y a donc une page qui permet d'écrire le contenu de la note, et un bouton enrgister afin de "terminer" le service de l'intent et de sauvegarder la note.
```
* Add intent for editor view
```
> Add intent for editor view

- package.json
- src/components/intents/SaveButton.jsx
- src/lib/collab/schema.js
- yarn.lock
```
* Upgrade cozy-interapp from 0.8.0 to 0.8.1
* Spread the id of the doc created to the service
* Schema version wasn't present on default schema
```
> Spread the id of the doc created to the service

- src/styles/index.css
Action list is not considered as a "block" so it doesn't get the right margin-bottom.
The result was that, when an action list was at the bottom at the text-area, the toolbar was overridden it.
This fix the issue.
> fix: Add margin-bottom to actionList

- src/components/notes/editor.jsx
When we format the document, we update the version if necessary. In this case, it updates the io.cozy.files document, which then requests the file a second time. As the two conditions to display the editor are no longer met, this hides it. The editor before hide force save to avoid data lost when closing the page. This relaunch an other request. This created an endless loop where only the loading state was displayed.
This commit corrects this problem by checking whether the object exists instead of checking the state of the request.
> [VO-126] fix: Infinite loop after version update

- src/components/notes/NoteProvider.jsx
This PR addresses a critical issue where the application entered an infinite loop of attempting to update a note's schema after a failure was encountered. The root cause was identified as a missing condition to halt further attempts once a `404 Not Found` error occurred during the schema update process.
**Modifications:**
- Introduced a conditional check to prevent the `updateSchema` function from being invoked if the previous attempt resulted in a 'failed' status.
- Ensured that the application does not retry the update after setting the status to 'failed', effectively breaking out of the infinite loop.
**Code Changes:**
```javascript
// Added check to prevent update if the last status was 'failed'
if (status !== 'failed') { 
doc = await serviceClient.updateSchema(noteId, schemaOrdered) …
```
> fix: avoid infinite loop on schema update (VO-312)

- src/ui/DropdownMenu/index.tsx
* In mobile view, the dropdown menu in the toolbar was displaying in part below the viewport. It will now flip automatically and display above the toolbar if needed
> fix: set shouldFlip to true in dropdownMenu (VO-582)

- src/targets/intents/index.jsx
It was causing a blank screen in mespapiers app when creating a note : "Cannot use useBreakpoints without BreakpointsProvider. The component must have a BreakpointsProvider above it."
```
* Fix intent to create note
```
> fix: Add missing BreakpointsProvider in intent

- package.json
- src/targets/browser/index.ejs
- src/targets/mobile/DOCS.md
Something started but never finished ? 🤷‍♂️
```
*
*
* Clean unused code
```
> refactor: Clean unused mobile target

- src/components/app.jsx
In the case of public sharing, we try to get an intent, which redirects to the sso as the recipient is not logged in. And this redirection is blocked by the CSP, so it silently fails.
> fix: Do not use dataproxy for public sharings
